### PR TITLE
Create gh-ff25-flag-of-portugal.json

### PR DESCRIPTION
**Pull request by PauloAlves311**

### CODE REVIEW

**Comment by AnonymousRandomPerson** [comment]
Sorry, but I'm not removing the Discords. I'm aware that controversy occurred with this artwork, but that doesn't justify erasing them.

**Comment by AnonymousRandomPerson** [comment]
If you'd like to discuss this further and give more details about this, you are welcome to join our Discord.

**Comment by PauloAlves311** [comment]
It is shameless self-promoting of discords which only were created because the r/portugal subreddit was in protest with the api changes, so they did not help in organize. The other discords did help a bit, but it was mostly streamers. 

I dont think they should stay since those pixels were not placed by the admins or streamers but by the users of reddit. Thus I dont think the discord should be promoted, specially not on every item inside the flag.

**Comment by AnonymousRandomPerson** [comment]
I've taken the liberty to join both Discord servers to verify your statement. It is clear that TugaPlace was activity working on the Portuguese flags and organizing users, so they will stay. The other Discord server appears to have concentrated on placing azulejos only, so I will remove them from the main Portuguese flags.

**Pull request closed without merging**
